# djaydev/ccextractor:latest

# complication stage
FROM alpine:3.12 AS builder

# install dependencies
RUN apk add pkgconf cmake automake autoconf \
    bash git build-base tesseract-ocr-dev \
    utf8proc-dev libpng-dev freetype-dev

# compile ccextractor
RUN git clone https://github.com/CCExtractor/ccextractor.git && \
    cd ccextractor/linux && \
    ./autogen.sh && \
    ./configure --enable-ocr && \
    make

# release stage
FROM alpine:3.12

# install dependencies
RUN apk add tesseract-ocr utf8proc libpng freetype && \
    # cleanup
    rm -rf /var/cache/apk/* /tmp/* /tmp/.[!.]*

# copy ccextractor from complication stage
COPY --from=builder /ccextractor/linux/ccextractor /usr/local/bin
