# djaydev/ccextractor:latest

# complication stage
FROM alpine:3.12 AS builder

# install dependencies
RUN apk add pkgconf cmake automake autoconf \
    bash git build-base tesseract-ocr-dev \
    utf8proc-dev libpng-dev freetype-dev -y

# compile ccextractor
RUN git clone https://github.com/CCExtractor/ccextractor.git && \
    cd ccextractor/linux && \
    ./autogen.sh && \
    ./configure --enable-ocr && \
    make

# release stage
FROM alpine:3.12

# install dependencies
RUN apt update && \
    apt install libfreetype6 libutf8proc2 tesseract-ocr -y && \
    # cleanup
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf \
    	/tmp/* \
    	/var/lib/apt/lists/* \
    	/var/tmp/*

# copy ccextractor from complication stage
COPY --from=builder /ccextractor/linux/ccextractor /usr/local/bin
